name: polaris_meter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1


environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  chopper: ^7.2.0
  auto_route: ^8.0.3
  # Dependency Injection
  injectable: ^2.4.1
  get_it: ^7.6.4
  # Bloc for state management
  bloc: ^8.1.4

  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1

  image_picker: ^1.0.7

  # DB
  path_provider: ^2.1.2

  # Hive DB

  hive: ^2.2.3
  hive_flutter: ^1.1.0


  json_annotation: ^4.8.1

  connectivity_plus: ^6.0.1
  flutter_dotenv: ^5.1.0
  minio_flutter:

#  minio_flutter:
#    git:
#      url: https://github.com/subhashDev11/minio_flutter.git
#      ref: main



#
#dependency_overrides:
#  http: any



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  chopper_generator: ^7.2.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  analyzer: ^6.4.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  # Hive Generator
  hive_generator: ^2.0.1








flutter:


  uses-material-design: true

  assets:

    - config/